### ISSUE TITLE
Allow axis to be something other than model units. 

### ISSUE THREAD

**Issue by mpound** [mpound/pdrtpy#3]
i.e. apply unit conversion to axes as well as image data.

**Comment by NanoExplorer** [comment]
I implemented something like this in order to display the y axis of `overlay_all_ratios` in terms of G_0 instead of ergs/s/cm^2. Do you have an interface in mind to pass the desired units to the various functions? I gave `_plot_no_wcs` an additional kwarg that I called `yaxis_unit`---that way I could pass `yaxis_unit="Habing"` to any of the functions that rely on `_plot_no_wcs`. 

I was thinking I could clean up the interface, add the same check to the x axis and send you a pull request if you want.

**Comment by mpound** [comment]
Originally I had in mind a keyword axis_units=[xunit,yunit]  but thinking about it your implementation makes more sense because the yaxis is the one that most people may  want to change.   Almost no one will want to change the density units.  Please proceed leaving defaults axis units as is.  Thanks.

**Comment by mpound** [comment]
Also added custom LaTeX labels for axes.
